[package]
name = "globby"
version = "0.2.3"
edition = "2024"

# Metadata for Cargo publishing
description = "Heavily opinionated glob matching library"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Globby"

[dependencies]
parsy = "0.15.2"
regex = "1.11.1"
